string state    # the state of the robot, e.g. '{"robot": "tall", "task": "uv"}'
bool update_restricted_map # define to update or not after evaluation

---

bool success
string restricted_tmap      # the map without the nodes/edges which does not satisfy the restrictions according to the state