string edge_id        # only used when calling service /topological_map_manager2/update_edge_action
string action_name    # if calling service /topological_map_manager2/update_action then is the action for which you are setting the type and goal for every edge in map
string action_type    # e.g. move_base_msgs/MoveBaseGoal
string goal           # json string setting the args of the goal
---
bool success
