string edge_id
string param_name         # namespace of the param is the edge's action
string param_value        # python uses its eval function to determine the type unless it is a string
bool value_is_string
---
bool success
string message
