default_behavior_tree: /opt/ros/$ROS_DISTRO/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml

# Custom edge behavior assignment for this deployment.
# Edges not listed here use the default_behavior_tree.
edge_behaviors: []
