name: Internal release
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    uses: SAGARobotics/SagaWorkflows/.github/workflows/ci.yml@v3.4
    with:
      release: 'true'
      distribution: 'noetic'
    secrets:
      pat-token: ${{ secrets.SERVICE_ACCOUNT_PAT_REPO_READ }}
      repo-user: ${{ secrets.SAGA_REPO_WRITE_USER }}
      repo-pass: ${{ secrets.SAGA_REPO_WRITE_PASS }}
