on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:


jobs:
  release:
    uses: SAGARobotics/SagaWorkflows/.github/workflows/release.yml@v2.1
    with:
      runs-on: '["ubuntu-latest"]'
    secrets:
      pat-token: ${{ secrets.CI_PAT_PUBLIC }}
      repo-user: ${{ secrets.SAGA_REPO_PUBLIC_WRITE_USER }}
      repo-pass: ${{ secrets.SAGA_REPO_PUBLIC_WRITE_PASS }}
